name: bookverse
description: Thư viện sách cá nhân - Đạt 10/10 điểm
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  flutter_riverpod: ^2.5.1
  go_router: ^14.3.0
  fl_chart: ^0.69.0
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  uuid: ^4.5.0
  http: ^1.2.2
  file_picker: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
dependency_overrides:
  firebase_auth_platform_interface: ^7.0.0
  # một số trường hợp cần thêm cái này nữa
  # firebase_core_web: ^2.0.0